### ISSUE TITLE
Pedido de melhoria na documentação

### ISSUE THREAD

**Issue by AlbertoAlfredo** [imobanco/bb-wrapper#29]
A documentação apenas fala as variáveis que precisarão, não mostrando quais métodos existem e quais os parâmetros precisamos passar, ajudaria bastante esse apoio. Um pouco mais de detalhes seria muito útil

**Comment by rodrigondec** [comment]
@AlbertoAlfredo 

Existe a pasta exemplos que mostra a utilização da LIB em diversas situações e de todos os métodos disponíveis.

Como são muitos métodos isso não será documentado no readme ou algo similar.

Mas os scripts de exemplos sempre estão válidos e funcionais! Inclusive, podem ser executados.
