### ISSUE TITLE
Erro na baixa 4125718.1 e no registro: 4432632

### ISSUE THREAD

**Issue by marcoazcabral** [imobanco/bb-wrapper#46]
Após vários dias funcionando normalmente, em 31/08 a baixa dos títulos em aberto, situação normal, passou a retornar:

raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: {'errors': [{'code': '4125718.1', 'message': 'Internal Server Error'}]} for url: https://api.sandbox.bb.com.br/cobrancas/v2/boletos/00031285579999999067/baixar?gw-dev-app-key=xxxx

e a baixa apresenta o erro:
raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: {'erros': [{'codigo': '4432632', 'versao': '1', 'mensagem': 'Convenio/Carteira/Variacao nao cadastrado.', 'ocorrencia': 'CHOM00000075256534170101'}]} for url: https://api.sandbox.bb.com.br/cobrancas/v2/boletos?gw-dev-app-key=xxx

Seria esse um erro interno no próprio BB?

**Comment by rodrigondec** [comment]
Sim, esse é um erro do próprio servidor do BB, para contato com eles utilizar o https://forum.developers.bb.com.br/.

Sofremos também instabilidade de erros 500 da API do BB e abrimos um tópico questionando pra esse dia 31/08.

Foi nos passado aqui https://forum.developers.bb.com.br/t/erro-500-no-cash-out/21594/5?u=rodrigo3
> sobre os demais erros relatados, eles ocorreram na madrugada devido a uma falha em nossa base de dados. Processo foi restaurado.
